#!/bin/bash
export CLEAN=0
export IMPORT=0
export SRCTREEOVERR=0
export FILEDIR="files/"
export CONFIGPATH="configs"  
export CUSTCONF="customerconfigs"
export VERBOSE=0
export DEVELOPER=0
export TMPDIR="/tmp/builder/"
LOCAL_MIRROR="http://mirror.inteno.se/mirror"

v() {
	[ "$VERBOSE" -ge 1 ] && echo "$@"
}
usage() {
        echo
        echo 1>&2 "Usage: $0 [OPTIONS] BoardConfig Customerconfig"
        echo
	echo "  -c,  remove all files under ./files and import from config "
	echo "  -v,  verbose"
	echo "  -d,  developer, will rewrite git url to use inteno gitolite server and use some closed source packages."
	echo "  -u, Update customer config before applying"  
	echo "	-p, set profile (if exists)"
	echo "	-t, use latest git tag and number of commits since as version for the build"
	echo "  -s, enable 'Package source tree override'"
	echo 
        echo "BoardConfig ex "
	ls -1 configs
	if [ -d "$CUSTCONF/$1" ]; then
        echo "Customerconfig ex"
	ls  $CUSTCONF/*
	fi  
	echo
	echo "Example ./genconfig vg50 TELIA" 
        echo "(if no customerconfig is chosen the Inteno Config will be used)"
	echo 	
        exit 127
}

use_local_mirror()
{
    if wget -T 3 -t 2 -O /dev/null $LOCAL_MIRROR >/dev/null 2>/dev/null
    then
	echo "mirror [$LOCAL_MIRROR] exists. Using local mirror"
	sed -i "s;CONFIG_LOCALMIRROR=.*;CONFIG_LOCALMIRROR=\"$LOCAL_MIRROR\";" .config
    else
	echo "mirror [$LOCAL_MIRROR] don't exists. Not using local mirror"
    fi
}

generate_config()
{
    DIFFFILE="$1"
    MASTERFILE="$2"
    while read p; do
	v  "$p"
	sed -r -i  "$p" $MASTERFILE
    done < $DIFFFILE
}

set_profile(){
	local PROFILE="$1"; 
	local MASTERFILE="$2"; 
	echo "setting profile: $PROFILE"; 
	cat "$PROFILE" >> "$MASTERFILE"
	make defconfig > /dev/null
}

create_and_copy_files()
{
    local BOARDTYPE=$1
    local CUSTOMER=$2
    v "cp  $CONFIGPATH/MASTER/config .config"
    cp  $CONFIGPATH/MASTER/config .config
    if [ $DEVELOPER -eq 1 ]; then
		if [ ! -d "$CUSTCONF" ]; then
			git  clone  git@ihgsp.inteno.se:customerconfigs
		elif [ $IMPORT -eq 1 ]; then
			cd customerconfigs
			v "git pull"
			git pull
			cd ..
		fi
    fi

    if [ ! -d "$CONFIGPATH/$BOARDTYPE" ]; then
		echo "Hardware profile does not exist"
		exit 1
    elif [ -n "$CUSTOMER" -a ! -d "$CUSTCONF/$BOARDTYPE/$CUSTOMER/" -a $DEVELOPER -eq 1 ]; then
		echo "Customer profile does not exist"
		exit 1
    fi
    v  "Config $BOARDTYPE selected"
    if [ ! -d "$FILEDIR" ]; then
		mkdir $FILEDIR
		elif  [ -d "$FILEDIR" -a $CLEAN -eq 1 ]; then
		v "rm -rf $FILEDIR*"	
		rm -rf $FILEDIR*
    fi

    # developer mode selected ?
    if [ $DEVELOPER -eq 1 ]; then

	##### if developer change to full source packages
	[ -e "$CONFIGPATH/DEVELOPER/developer.diff" ] && generate_config $CONFIGPATH/DEVELOPER/developer.diff .config

	# rewrite url to clone with ssh instead of http
	echo "CONFIG_GITMIRROR_REWRITE=y" >>.config
    fi

    # first build config based on boardid
    if [ -d "$CONFIGPATH/$BOARDTYPE/fs" ]; then
        v "cp -rLp $CONFIGPATH/$BOARDTYPE/fs/* $FILEDIR"
        cp -rLp $CONFIGPATH/$BOARDTYPE/fs/* $FILEDIR 2>/dev/null
    fi
    if [ -e "$CONFIGPATH/$BOARDTYPE/$BOARDTYPE.diff" ]; then
        v "Apply $CONFIGPATH/$BOARDTYPE/$BOARDTYPE.diff"
        generate_config $CONFIGPATH/$BOARDTYPE/$BOARDTYPE.diff .config
    fi
    echo $BOARDTYPE > .current_config_file

	# second add diff for customer config if if customer code
	if [ -n "$CUSTOMER" ]; then
		echo "$BOARDTYPE $CUSTOMER" > .current_config_file
		if [ -d "$CUSTCONF/$BOARDTYPE/$CUSTOMER/fs" ]; then
			v "cp -rLp $CUSTCONF/$BOARDTYPE/$CUSTOMER/fs/* $FILEDIR"
			cp -rLp $CUSTCONF/$BOARDTYPE/$CUSTOMER/fs/* $FILEDIR
		fi
		if [ -e "$CUSTCONF/$BOARDTYPE/$CUSTOMER/$BOARDTYPE.diff" ]; then
			v "Apply $CUSTCONF/$BOARDTYPE/$CUSTOMER/$BOARDTYPE.diff"
			generate_config $CUSTCONF/$BOARDTYPE/$CUSTOMER/$BOARDTYPE.diff .config
		fi
	fi

	if [ -n "$PROFILE" ]; then 
		if [ -e "$CUSTCONF/$BOARDTYPE/$CUSTOMER/$PROFILE.profile" ]; then
			set_profile $CUSTCONF/$BOARDTYPE/$CUSTOMER/$PROFILE.profile .config
		elif [ -e "$CUSTCONF/$BOARDTYPE/$PROFILE.profile" ]; then 
			v "Using generic board profile for $PROFILE"
			set_profile $CUSTCONF/$BOARDTYPE/$PROFILE.profile .config
		elif [ -e "$CUSTCONF/$PROFILE.profile" ]; then 
			v "Using generic profile for $PROFILE"
			set_profile $CUSTCONF/$PROFILE.profile .config
		elif [ -e "$CONFIGPATH/$BOARDTYPE/$PROFILE.profile" ]; then
			set_profile configs/$BOARDTYPE/$PROFILE.profile .config
		elif [ -e "$CONFIGPATH/MASTER/$PROFILE.profile" ]; then
			set_profile configs/MASTER/$PROFILE.profile .config
		else
			echo "ERROR: profile $PROFILE does not exist!"
			exit 1
		fi
	else 
		v "No profile selected! Using default."
	fi	

	if [ -n "$USE_TAG" ]; then 
		local GIT_TAG=$(git describe --abbrev=0 --tags)
		#local GIT_REVISION=$(($(git rev-list --count HEAD) - $(git rev-list --count $GIT_TAG)))
		#echo "CONFIG_TARGET_VERSION=\"${GIT_TAG}.${GIT_REVISION}\"" >> .config
		#echo "Set version to \"${GIT_TAG}.${GIT_REVISION}\""
		echo "CONFIG_TARGET_VERSION=\"${GIT_TAG}\"" >> .config
		echo "Set version to \"${GIT_TAG}\""
	fi	


    # Enable Pckage source tree override if selected
    [ $SRCTREEOVERR -eq 1 ] && \
        sed -i 's/# CONFIG_SRC_TREE_OVERRIDE.*/CONFIG_SRC_TREE_OVERRIDE=y/' .config


    # validate the .config against dependency rules.
    make defconfig

    if [ "$PROFILE" == "juci" ]; then
	sed -i '/CONFIG_PACKAGE_luci-lib-core_source=y/d' .config
	sed -i '/CONFIG_PACKAGE_luci-lib-nixio_notls=y/d' .config
    fi
}

####### main #####
if [ ! -e tmp/.iop_bootstrap ]; then
    echo "You have not installed feeds. Running genconfig in this state would create a non functional configuration."
    echo "Run: ./scripts/iop_feeds_update.sh"
    exit 0
fi

if [ $# -eq 0 ]; then
    echo Current profile:
    cat .current_config_file
    echo "Try ./iop_get_config.sh -h' to get instructions if you want to change current config"
    exit 0
else
    
    while [ -n "$1" ]; do 
	case "$1" in

	    -c) export CLEAN=1;;
	    -u) export IMPORT=1;;
	    -d) export DEVELOPER=1;;
	    -v) export VERBOSE="$(($VERBOSE + 1))";;
		-p) export PROFILE="$2"; shift;; 
		-t) export USE_TAG=1;; 
	    -s) export SRCTREEOVERR=1;;
	    -h) usage;;
	    -*)
		echo "Invalid option: $1 "
		echo "Try  -h' for more information."
		exit 1
		;;
	    *) break;;
	esac
	shift;
    done
    [ -d $TMPDIR ] || mkdir $TMPDIR
    create_and_copy_files "$1" "$2"
    [ -d $TMPDIR ] && rm -rf $TMPDIR
    use_local_mirror
fi
