#!/bin/sh /etc/rc.common

START=01
STOP=99

NAME=iwatchdog
PROG=/sbin/iwatchdog

fill_in_default()
{
    /sbin/uci add system log
    /sbin/uci rename system.@log[-1]=watchdog
    /sbin/uci set system.watchdog.enable=no
    /sbin/uci commit
}

start()
{
    enable=$(/sbin/uci get system.watchdog.enable)
    case $enable in
       0|no|NO|false|FALSE)
           exit 0
           ;;
	"")
	    fill_in_default
	    exit 0
	    ;;
     esac
    
    service_start $PROG
}

stop()
{
    service_stop $PROG
}
