#!/bin/sh /etc/rc.common

START=01
STOP=99

NAME=iwatchdog
PROG=/sbin/iwatchdog

start()
{
    enable=$(/sbin/uci get system.watchdog.enable)
    case $enable in
       0|no|NO|false|FALSE)
           exit 0
           ;;
    esac
    
    service_start $PROG
}

stop()
{
    service_stop $PROG
}
