#!/bin/sh
# Copyright (C) 2009-2012 OpenWrt.org
# Copyright (C) 2010 Vertical Communications
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

blkdev=`dirname $DEVPATH`
if [ `basename $blkdev` != "block" ]; then

    device=`basename $DEVPATH`
    mountpoint=`sed -ne "s|^[^ ]*/$device ||; T; s/ .*//p" /proc/self/mounts`

    # Determine mount path
    usbno=$(echo $DEVPATH | awk -F'/' '{print$7}')
    case "$usbno" in
	*:*) usbno=$(echo $DEVPATH | awk -F'/' '{print$6}') ;;
    esac
    mnfct="$(cat /sys/bus/usb/devices/$usbno/manufacturer | sed 's/ //g')"
    prdct="$(cat /sys/bus/usb/devices/$usbno/product | sed 's/ //g')"
    mnthd="${mnfct:-$prdct}"
    serial="$(cat /sys/bus/usb/devices/$usbno/serial | sed 's/ //g')"

    case "$ACTION" in
	add)
		grep -q "/dev/$device" /proc/swaps || grep -q "/dev/$device" /proc/mounts || {
			case "$device" in
				mtdblock*) ;;
				*)
					mntdir="$mnthd$serial"
					mkdir -p /mnt/$mntdir
					( mount /dev/$device /mnt/$mntdir -o umask=0,noexec || mount /dev/$device /mnt/$mntdir -o noexec|| ntfs-3g /dev/$device /mnt/$mntdir -o noexec) 2>&1 | tee /proc/self/fd/2
					type="$(cat /proc/mounts 2>/dev/null | grep "$device" | grep "$device" | awk '{print $3}')"
					echo "/dev/$device /mnt/$mntdir" "$type" >> /var/usbmounts
					[ -n "$mntdir" ] && ubus send usb "{\"action\":\"mount\",\"device\":\"$device\",\"mountpoint\":\"/mnt/$mntdir\"}" 2>/dev/null
				;;
			esac
		}
		;;
	remove)
		umount /dev/$device
		umount $mountpoint
		rm -rf $mountpoint
		sed -i "/$device/ d" /var/usbmounts
		[ -n "$device" ] && ubus send usb "{\"action\":\"unmount\",\"device\":\"$device\",\"mountpoint\":\"$mountpoint\"}" 2>/dev/null
		;;
    esac	

fi

