#!/bin/sh 

toggle=1
last_error=0
while true
do
	errs=$(cat /proc/net/dev | grep eth2 | tail -1 | awk '{print $4}')
	if [ $errs -gt $((last_error + 100)) ]
	then
		last_error=$errs
		if [ $toggle -eq 1 ]
		then
			toggle=0
			ethctl phy ext 0x01 0x1c 0x8e00
	    	else
			toggle=1
			ethctl phy ext 0x01 0x1c 0x8c00
	    	fi
	fi
	sleep 10
done



